services:
  
  app1:
    build: ./app1
    container_name: flask-app1
    ports:
      - "5001:5000"
    depends_on:
      - app2
    networks:
      - backend


  app2:
    build: ./app2
    container_name: flask-app2
    ports:
      - "5002:5000"
    networks:
      - backend

networks:
  backend:
    driver: bridge

  